danielromeroauk/git-desde-cero

README.md

La nueva sección permitirá a la gente practicar haciendo **pull request** para agregarse a la lista de personas que están aprendiendo sobre Git, será similar a firmar el libro de asistencia en un lugar turístico e histórico.

Crea la sección "Personas aprendiendo sobre Git"

---

README.md

haciendo las practicas de tus vídeos y añadiendo mi nombre en el README.md

añadiendo mi nombre en el README.md

---

README.md

Aprendiendo Git - Dejando la marca en el libro de visitas

Creando nombre dentro del listado de personas. 

---

README.md

Hola acabo de hacer **pull request** para añadirme a lista de personas que estamos aprendiendo sobre Git.

Se agrego un nuevo integrante a la lista de persona "Aprendiendo Git"

---

README.md

Se solicita agregar a la lista de personas a un nuevo estudiante del mini curso de GIT desde cero.

Agrega nombre de nuevo estudiante

---

README.md

Me agregué a la lista de personas que están aprendiendo sobre Git, haciendo pull request.

Agrega nuevo perfil en la lista (Roberto Méndez)

---

README.md

Hola estaba practicando con tu curso, un saludo, muy bueno.

Agregue mi nombre para practicar, saludos

---

README.md

Demostrando lo aprendido

---

README.md

Practicando `pull request` para neófitos

Saludos, buen tutorial para empezar!

---

README.md

Complete el tutorial asi que agregue mi nombre a la lista de personas

Inserccion de mi nombre Gerardo

---

README.md
index.html

Añado estilos básicos utilizando **Css** al archivo **index.html**

Añade estilos "Añado estilos css básicos"

---

README.md

La nueva seccion , me agregue en la lista de personas que estan aprendiendo fork

Practicando fork

---

README.md

esta es una prueba de pull request

agregado a la lista

---

README.md

Añadi mi firma al archivo Readme, muchas gracias por tu curso y compartir tu conocimiento.

Alberto Pimentel firma

---

README.md

Hola, estoy agregando al archivo README.md mi nombre y usuario de GitHub.

Hola estoy aprendiendo Git!

---

README.md

Agrege mi nombre y link de mi cuenta de  github en el archivo REAME.md

Me agrege al archivo README.md

---

README.md

Me añado a las personas que aprenden :D

Añadí Enzo Olórtegui

---

README.md

Agregue mi nombre y URL a la lista para aprender a hacer un **pull request**, el cual es similar a firmar un libro de asistencia en un lugar turístico e histórico.

Agregue mi nombre y URL

---

README.md

Aquí les dejo un curso de **DevCode**

Nuevo curso

---

README.md

Hola, gracias por el curso he aprendido mucho, le agradezco y le envío mi granito de arena.

uno mas que esta aprendiendo

---

README.md

Hola Daniel, estoy añadiendo mi nombre al libro de visitas, Muchas gracias por el vídeo me sirve para estos días de cuarentena.
**Saludos desde Perú**

Se agrego el nombre de raul martinez

---

README.md

Enviar pull request con mi nombre

Personas aprendiendo sobre GIT

---

README.md

He practicado el proceso para realizar **pull request**.

Nombre agregado a la lista de asistencia de un lugar turístico e historíco.

---

README.md

Agregando la firma de una persona.

Andri Bonilla firma(#34)

---

README.md

Agradeciendo el espacio por permitirme practicar **pull requests**.

Agregarme a la lista de practicantes

---

README.md

Agregué mi nombre en la lista de personas que estan aprendiendo sobre Git
_PD: Muchas gracias por los videos, sirven demasiado._

Andrik Martínez firma

---

README.md

santaigo kaz aprendiendo github

---

README.md

**Muchas gracias** por compartir tu conocimiento. Sin duda me ayudaste mucho.

Un nuevo aprendiz. gracias por todo!

---

README.md

Practicando git desde cero de: https://www.youtube.com/watch?v=xl3nxfbGkzY&list=PLmUnyBCRHkvUPkrsseI1SmMtYgfc-f8Kn&index=9

Crea la seccion "Personas aprendiendo sobre Git"

---

README.md

Juan Pablo Sala firma (#45)

---

README.md

En este commit me agregue a la lista de personas aprendiendo git.

Nueva Persona

---

README.md

la nueva sección que se creo con anterioridad para que las personas sigan aprendiendo sobre git, ya contiene mi nombre y link por si quieren asociarse. Ya que con esto practicare mi **Pull request** en primeras instancias

Crea la seccion con mi nombre

---

README.md

Agregue nombre y link a la sección "Personas aprendiendo Git"

Agregue nombre a la sección "Personas aprendiendo Git"
